config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[new create index destroy]
  resources :users, only: %i[new create]
  resources :sessions, only: %i[create]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :delete_all

  # attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: 'Please login to access' if current_user.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: %i[new create destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Created successfully'
    else
      render :new, notice: 'Failed to create'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new() end

  def create
    user = User.find_by_email(params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersClubhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="margin-center">
        <%= link_to "Home", root_path, class: "logo" %>
        <nav>
          <ul>
            <% if current_user %>
              <li>Hi, <span class="purple"><%= current_user.name %></span></li>
              <li>
                <%= link_to "Log out", logout_path, class: "danger-text" %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign Up", signup_path, class: "purple" %>
              </li>
              <li>
                <%= link_to "Login", login_path, class: "green" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer>&copy; Kamba <%= Date.current.year %></footer>
  </body>
</html>

app/views/posts/index.html.erb
<main>
  <h1 class="title">Users thoughts/qoutes</h1>
  <section class="cards">
    <% @posts.each do |post| %>
      <div class="card">
        <p><%= post.text %></p>

        <% if current_user %>
          <h5>By: <span class="purple"><%= post.user.name %></span></h5>
          <%= button_to "Delete", post, method: :delete, disabled: current_user != post.user, class: "btn danger" %>
        <% end %>
      </div>
    <% end %>
  </section>

  <% if current_user %>
    <%= link_to "Add new post", new_post_path, class: "btn" %>
  <% end %>

</main>

app/views/posts/new.html.erb
<section class="form-section">

  <h4 class="title margin-center">Add new post</h4>

  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div class="error-messages">
        <ul>
          <% @posts.errors.each do |error| %>
            <li><%= error.full_messages %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.text_area :text, required: true, placeholder: "Enter your post here" %>
    </div>
    <div>
      <%= f.submit "Add", class: "btn" %>
    </div>

  <% end %>
</section>

app/views/users/new.html.erb
<section class="form-section">
  <h2 class="title margin-center">Sign Up</h2>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error-messages">
        <h4>Form is invalid</h4>
        <ul>
          <% @user.errors.full_messages.each do |m| %>
            <li><%= m %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label :name %>
      <%= f.text_field :name, required: true, placeholder: "Enter your name" %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.email_field :email, required: true, placeholder: "Enter your email" %>
    </div>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password, required: true, placeholder: "Enter password" %>
    </div>

    <div>
      <%= f.submit "Sign Up", class: "btn" %>
    </div>

  <% end %>
</section>